### PR TITLE
Fix clickable cards

### LINKED ISSUE #110: Remove clickaable cards where not needed
Great feature was added with #108 but that had the side effect of making all cards clickable, even when they probably should not be. Namely, the cards in the about page and events page.

Should probably have 2 card components, one with a link and one without. Or making the card not clickable if there is no link.

### PR DESCRIPTION
**Pull request by unknown**
Fixes https://github.com/BUGS-NYU/bugs-nyu.github.io/issues/110

### CODE REVIEW

File: src/components/Card.tsx [hunk 1]
```diff
@@ -27,38 +27,22 @@ const classes = {
...
-    );
-  },
-);
+function Card({ children, size = 'normal', radius = 'normal', shadow = 'none', link }: CardProps) {
+  const className = classNames(
+    classes.base,
+    classes.size[size],
+    classes.radius[radius],
+    classes.shadow[shadow],
+  );
```
Comment (nedjulius) [inline src/components/Card.tsx:36]:
```suggestion
  );
  
```

File: src/components/Card.tsx [hunk 2]
```diff
@@ -27,38 +27,22 @@ const classes = {
...
+  if (link === undefined) {
+    return <div className={className}>{children}</div>;
+  }
```
Comment (nedjulius) [inline src/components/Card.tsx:40]:
```suggestion
  }
  
```

File: src/pages/projects.tsx [hunk 3]
```diff
@@ -1,111 +1,111 @@
...
+      <h2 className='text-4xl font-bold'>Projects</h2>
+      <p className='mt-4'>
+        BUGS is meant to be a collaborative and inclusive environment for everyone. We&apos;re
+        always welcome to hear your ideas and work on new projects. Here are some past projects we
+        have worked on.
+      </p>
+      <div className='mt-12 grid grid-cols-1 gap-4 md:grid-cols-2'>
+        <Card shadow='normal' link='https://nyusyllabi.com/'>
+          <div className='h-full flex flex-col'>
+            <h2 className='text-xl font-bold'>NYU Syllabi</h2>
```
Comment (nedjulius) [inline src/pages/projects.tsx:20]: idk maybe it would make sense to extract all of the static data into some array constant and then just map; we would avoid repeating same HTML structs and it would be easier to extend the contents later. wdyt?

**Review by nedjulius — APPROVED** [review]
some small nits

File: src/pages/projects.tsx (hunk 3 above)
Comment (unknown) [reply src/pages/projects.tsx:20]: Yeah that's a good idea, I can open a new issue. Honestly, I'm not sure how this file was added to my commit because I never changed the file.

Comment (unknown) [reply src/pages/projects.tsx:20]: I'll merge this PR now though, TY for reviewing.
